### ISSUE TITLE
breaks when it encounters a directory

### ISSUE THREAD

**Issue by wickett** [yearofmoo/Simple-S3#1]
When simple-s3 encouters a directory to upload to s3, it breaks.  See below.

There is a directory called 'test' with a file called 'test.txt' inside of it.

Simple-S3: Uploading ./test as 'test' to 'mybucket'
/Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:329:in `read': Is a directory - ./test (Errno::EISDIR)
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/extensions.rb:329:in`send_request_with_body_stream'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:1921:in `exec'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:1317:in`block in transport_request'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:1316:in `catch'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:1316:in`transport_request'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:1293:in `request'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/connection.rb:45:in`block in request'
    from /Users/jwickett/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/net/http.rb:745:in `start'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/connection.rb:52:in`request'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:69:in `request'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:88:in`put'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/aws-s3-0.6.3/lib/aws/s3/object.rb:241:in `store'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/simple-s3-1.0.2/lib/simple-s3/simple-s3.rb:71:in`block in upload!'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/simple-s3-1.0.2/lib/simple-s3/simple-s3.rb:68:in `each'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/simple-s3-1.0.2/lib/simple-s3/simple-s3.rb:68:in`upload!'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/simple-s3-1.0.2/lib/simple-s3/simple-s3.rb:33:in `run!'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/gems/simple-s3-1.0.2/bin/simple-s3:3:in`<top (required)>'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/bin/simple-s3:19:in `load'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/bin/simple-s3:19:in`<main>'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/jwickett/.rvm/gems/ruby-1.9.3-head/bin/ruby_noexec_wrapper:14:in`<main>'

**Comment by matsko** [comment]
Fixed. Set the simple-s3 gem version to `~> 1.0.13` in your `Gemfile`.

Thank you for pointing this out.
