### ISSUE TITLE
Cannot upload to non US bucket

### ISSUE THREAD

**Issue by paulspencerwilliams** [yearofmoo/Simple-S3#3]
I've created an Ireland Region based S3 bucket, and configured simple-s3.yml to be like

s3_bucket: 'xxxx'
s3_access_key: 'blah'
s3_secret_key: 'blah'

If I try just the bucket name (cheryls-site) then I get:

Simple-S3: Uploading ./css/320andup.css as 'css/320andup.css' to 'cheryls-site'
/Users/will/.rvm/gems/ruby-1.9.3-p327/gems/aws-s3-0.6.3/lib/aws/s3/error.rb:38:in `raise': The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (AWS::S3::PermanentRedirect)

If I try the fqdn bucket endpoint, then I get:

Simple-S3: Uploading ./css/320andup.css as 'css/320andup.css' to 'cheryls-site.s3-website-eu-west-1.amazonaws.com'
/Users/will/.rvm/gems/ruby-1.9.3-p327/gems/aws-s3-0.6.3/lib/aws/s3/error.rb:38:in `raise': The specified bucket does not exist (AWS::S3::NoSuchBucket)

I believe the problem is when connecting to non US S3 buckets, you connect to the Region server first, and then specify the bucket name. 

I will fork / fix and try a pull request if that's ok...

**Comment by matsko** [comment]
You can now set the `s3_bucket_endpoint` configuration inside your `simple-s3.yml` file. The value should be the value obtained from the AWS bucket properties section under **Static Website Hosting** (copy the domain part of it before the tld and after the bucket subdomain).

First update the gem to `gem "simple-s3", "~> 1.0.17"` and then make sure that the `simple-s3` command points to the correct version (you can cd into the directory and out to refresh the RVM snapshot).

Let me know if this works for you.

**Comment by matsko** [comment]
OK I noticed you added it already? Let me know if it's working and I'll merge the two together.

**Comment by paulspencerwilliams** [comment]
Right, you fix in 1.0.17 works a treat. Please close my pull request and have a beer / drink of your choice! 

Thanks for incredible fast turn around.

**Comment by matsko** [comment]
All working now. So to confirm, please use version `1.0.20` or higher.

The new configuraiton syntax has been updated into the README as well.

```
s3_bucket_endpoint: "..."
```

And if you change the endpoint (by setting something else) then the tool will instruct you about the change in the command line.

`Simple-S3: Changing the bucket endpoint from 'XXXX' to 'YYYY'`

Thanks for pointing this out! :)

**Comment by paulspencerwilliams** [comment]
This issue is closed, but I still can't upload to s3 . Simple-S3 correctly outputs:

doing it
Simple-S3: Changing the bucket endpoint to: 'cheryls-site.s3-website-eu-west-1.amazonaws.com'
Simple-S3: Uploading ./css/320andup.css as 'css/320andup.css' to 'cheryls-site'
....
Simple-S3: Uploading ./robots.txt as 'robots.txt' to 'cheryls-site'
Simple-S3: Upload Completed!

However, no files are actually updated. I've deliberately tried invalid bucket names and endpoints, and still see the same 'working' output, but no files are uploaded...

My simple-s3.yml looks like - 
s3_bucket: 'cheryls-site'
s3_access_key: '...'
s3_secret_key: '...'
s3_bucket_endpoint: 'cheryls-site.s3-website-eu-west-1.amazonaws.com'

**Comment by matsko** [comment]
Try using this as your endpoint `s3-eu-west-1.amazonaws.com` or just `s3-website-eu-west-1.amazonaws.com`.

**Comment by matsko** [comment]
And upgrade it to version `1.0.20`.

**Comment by paulspencerwilliams** [comment]
Yep, combination of new software and configuring correctly work a treat! Cheers!

**Comment by matsko** [comment]
Can you point out which endpoint you used? Was it `s3-eu-west-1.amazonaws.com` or `s3-website-eu-west-1.amazonaws.com` ?

**Comment by paulspencerwilliams** [comment]
Yeah, It was s3-eu-west-1.amazonaws.com which worked perfectly.

**Comment by matsko** [comment]
Perfect. Thank you for your help :)
